#!/usr/bin/env bash

# Exit immediately if a command exits with a non-zero status
set -e

# Enforce strict variable lookups
set -u

echo "--------------------------------------------"
echo "⚓ Initializing Automated Monorepo Setup"
echo "--------------------------------------------"

# ==========================================
# 1. PREREQUISITE VALIDATION (Node, PNPM, UV, Python, Docker & Act)
# ==========================================
if ! command -v node &> /dev/null; then
    echo "❌ Error: 'node' runtime is not installed." >&2
    exit 1
fi

if ! command -v pnpm &> /dev/null; then
    echo "❌ Error: 'pnpm' package manager is not installed." >&2
    echo "💡 Install it globally by running: npm install -g pnpm" >&2
    exit 1
fi

if ! command -v uv &> /dev/null; then
    echo "❌ Error: 'uv' package manager is not installed." >&2
    echo "💡 Install it by running: curl -LsSf https://astral.sh | sh" >&2
    exit 1
fi

if ! command -v python3 &> /dev/null; then
    echo "❌ Error: 'python3' is not installed." >&2
    exit 1
fi

if ! command -v docker &> /dev/null; then
    echo "❌ Error: 'docker' container runtime engine is not installed." >&2
    exit 1
fi

if ! command -v act &> /dev/null; then
    echo "❌ Error: 'act' local GitHub Actions runner is not installed." >&2
    echo "💡 Install it by running: brew install nektos/tap/act" >&2
    exit 1
fi

echo "✅ Core runtimes detected: Node.js, pnpm, uv, Python, Docker, and Act."

# ==========================================
# 2. SAFETY CLEANUP
# ==========================================
echo "🧹 Cleaning up legacy caches and environment residues..."

# Cleans dynamic stale virtual environment residues generated by previous workspace provisions
rm -rf .venv_stale_* || true

if [ -d ".venv" ]; then
    RANDOM_ID=$((RANDOM))
    STALE_DIR=".venv_stale_${RANDOM_ID}"

    # Renames the directory to instantly unblock target creation names
    mv .venv "$STALE_DIR" || true

    # Injects a brief 1-second operational sleep to give the Unix system kernel
    # enough time to release any lingering file-descriptor holds applied by IDEs.
    sleep 1

    if [ -d "$STALE_DIR" ]; then
        rm -rf "$STALE_DIR" || true
    fi
fi

rm -rf .uv || true

if [ -d "projects" ]; then
    find projects -type d -name "node_modules" -prune -o -type d -name ".venv" -exec rm -rf {} + || true
fi

# ==========================================
# 3. PNPM WORKSPACE INSTALLATION
# ==========================================
echo "📦 Installing global workspace dependencies via pnpm..."
pnpm infra:install:global:workspace:dependencies

# ==========================================
# 4. PYTHON WORKSPACE RESOLUTION & SYNC
# ==========================================
# Leverages the official deterministic uv synchronization workflow.
# Using '--frozen' ensures total environment reproducibility across CI and local setups.
echo "🚀 Syncing Python dependencies and linking workspace subprojects..."
pnpm infra:install:global:python:dependencies

# ==========================================
# 5. MONOREPO QUALITY MATRIX VERIFICATION
# ==========================================
echo "🛡️ Executing unified quality verification pipeline..."

# Running sequential validations ensures strict error propagation across commands
pnpm lint:check:all
pnpm test:sast:all
pnpm test:unit:all

echo "--------------------------------------------"
echo "✅ Monorepo environment configured and validated successfully!"
echo "💡 All security checks and linters passed perfectly."
echo "--------------------------------------------"
